let Themes = [
    'aviator',
    'blueberry',
    'bulldog',
    'cake',
    'caribbean',
    'clouds',
    'celeste',
    'diable',
    'eevee',
    'flowers',
    'forest',
    'graylord',
    'haze',
    'holy',
    'kino',
    'laser',
    'lavandula',
    'lemon',
    'lime-sports',
    'lollipop',
    'mint',
    'nature',
    'paradise-orange',
    'purple-skies',
    'reverse-sky',
    'sky',
    'spring-melody',
    'strawberry',
    'tosca',
    'wood',
];

export {Themes};